### ISSUE TITLE
new "reveal zone" window style is glitched

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1073]
https://github.com/Cockatrice/Cockatrice/pull/1053#issuecomment-101653886 :

doesn't look that nice: 
![windows](https://cloud.githubusercontent.com/assets/9874850/7610165/ffa5e4c0-f97a-11e4-857d-f7345d95f306.png)

- different window decoration and buttons style than the default win style
- window head is off-placed and looks separated
- there is a light color shift on the left and right of the window

---
confirmed on `win` and `osx`

**Comment by ZeldaZach** [comment]
Was this fixed with the boundaries re-established by @ctrlaltca?

**Comment by tooomm** [comment]
no, the problem is still there:

![border](https://cloud.githubusercontent.com/assets/9874850/9992209/af091656-6070-11e5-9328-77017f46eb20.png)

**Comment by tooomm** [comment]
Nice explanation about the issue: https://github.com/Cockatrice/Cockatrice/issues/1575#issuecomment-143192520

**Comment by Fenrirthviti** [comment]
Strongly suspect that this has long since been fixed in Qt. 

That said, as Win7 is fully EOL and no longer supported by anything (Qt included), and if this bug does still exist in Qt, there's pretty much no chance of it getting fixed. Probably not a lot of value in keeping this issue open.

**Comment by tooomm** [comment]
@ebbit1q asked for an update on this
```
Client Version: 2.7.6-beta.2 (2020-11-23)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.6
System Locale: de_DE
Install Mode: Standard
```
Same issue persists, also on most recent Windows 10 20H2:
![Untitled](https://user-images.githubusercontent.com/9874850/100091655-328aff00-2e55-11eb-8c67-5924869a0952.png)


---

I copy @ctrlaltca's insights from the linked ticket here again:

>Let's try to clarify:
>
>   - Qt tries to match the current os's theme; it's not perfect, but it typically does a good job;
>   - A "Classic window" theme exists (http://doc.qt.io/qt-5/gallery-windows.html)
>  -  A "Windows Vista" (read: windows 7) theme exists (http://doc.qt.io/qt-5/gallery-windowsvista.html)
>   - No "Windows Metro" theme is shipped yet with qt. I Know old digia's qt-commercial version had such a theme, but it was far from being complete.
>   - Since no windows metro theme exists, qt is rendering the window using the best match: windows 7 theme. We won't be able to draw that window decorations differently, this must be fixed in qt.


>Real windows and dialogs's decorations (like preferences, edit sets, ..) are drawn by the operating system, so their aspect is correct. The "view zone" window is not really a window, it is drawn by qt to match the aspect of the os; we could make it a real window, but this could cause problems, like it going behind the game window

We could try making those real windows as we can prevent them from going to the background like the `About` window, `Debug Log` etc. already do. Those have only the closing `X` and don't allow to get minimized as well.
That would deal with the weird behavior that the `View library/gy/...` windows are not freely movable and are locked to the game area as well.

**Comment by ebbit1q** [comment]
The reason why we render these windows inside the play area is because they are part of the qgraphicsview allowing you to easily drag and drop items, changing this is possible but a major overhaul.

**Comment by Fenrirthviti** [comment]
I went back and compiled against 5.15.2 as I was curious since I hadn't seen this bug since like 5.9, and ran in to some even more bizarre behavior with these windows when the play area is maximized:

[video clip](https://pub.rachni.com/vid/2020-11-24_06-28-58.webm)

and other oddities when the window is not maximized:

[video clip 2](https://pub.rachni.com/vid/2020-11-24_06-30-06.webm)

The first clip is obvious, but the second clip the window jumps randomly to the right when attempting to click/drag it. I'll do some poking around and see if I can figure out what's going on here, as this is starting to look like it might be a bug in Cockatrice or the way these windows are being generated, and could potentially be something fixable on this end rather than Qt.

**Comment by ebbit1q** [comment]
yes, that's https://github.com/Cockatrice/Cockatrice/issues/3386

**Comment by ebbit1q** [comment]
the second issue you clipped is https://github.com/Cockatrice/Cockatrice/issues/2707

**Comment by tooomm** [comment]
So there are quite some issues related to the custom window rendering!
Maybe the major overhaul to keep drag and drop support while switching to real windows should be considered at one point.
