### ISSUE TITLE
Card images not centered proprely

### ISSUE THREAD

**Issue by lOEILl** [Cockatrice/Cockatrice#1202]
When a card is in play i can see through the bottom part of the card.
![cockatrice images](https://cloud.githubusercontent.com/assets/13174590/8506982/aeae2fea-21fd-11e5-9eb7-f2536a3404b1.png)

i know its not a major bug but i find it really annoying.

**Comment by poixen** [comment]
I know what this is. Quick fix.

**Comment by lOEILl** [comment]
any idea to when this is gonna be fixed ?

**Comment by poixen** [comment]
fixed in #1219

**Comment by Nightfirecat** [comment]
I'm still seeing this issue - though only for tokens - after installing the latest weekly (3189045): [screenshot](http://i.imgur.com/j8GEr2A.png)
