### ISSUE TITLE
Dead and inaccessible games

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#1669]
Assuming it isn't really hard to implement, this would be wonderful:
* "Buddies only" rooms of people whose buddy list I'm not on, and rooms of people whose ignore list I am on falling under "unavailable games" for the purpouses of the "show unavailable games" tickbox.
* A "make room invisible" tickbox that autoticks on when the room fills (and only ticks off manually).
The "autotick" would single-handedly get rid of AFK rooms, and already-started draft rooms.  
Upsides:  
Tons of free room. Rids of half the rooms so it's easier to find one, no more accidentaly joining a dead room/fired draft and taking a minute(or more) to find out. If it didn't tick on automatically, noone would use it and it would be ultimately pointless.  
Downsides:  
Hosts having to tick a box every time a) someone leaves before a draft starts / b) a normal game ends. In the case of drafts there are 6 people who can help the host in case of confusion. In the case of normal games, the host can(and usually will) just make a new room. Thinking hard, I can see a problem of people who want to use a room to play multiple people in a row and not fail to notice a tickbox, that unlikely scenario could be solved via a reminder window/box/something.

**Comment by tooomm** [comment]
The first one is not really possible as far as I know... it got mentioned here several times that you don't know on which people's lists you are on. I might be wrong though.
Maybe the client could pull the lists of all game creators that are visible in your filter list at the moment.

The second one is a neat way of handling drafts and other rooms!
I don't see your downsides problematic at all. People need to get familiar with the program and interface they use. Shouldn't be too much of a deal, the tick box needs to be placed and labeled well for sure.
I really like your idea here!!
The tick box could be inactive/grayed out unless it gets ticket automatically as well.

**Comment by Daenyth** [comment]
I think that, not the details, but the spirit, of these requests would be fully solved by #622

**Comment by tooomm** [comment]
As I understand both issues (speaking of @LethalPigeon7's 2nd idea and #622), they are not related and user manageable server rooms doesn't solve "games-you-don't-want-to-join" as well as dead/old game rooms...
What he reported here is about an additional feature for every **game room** to make people not join old/inactive/"started" games because every unfilled game shows up in the game list right now.

It could be matched with #806 at best. But while #806 is more of a server management or general moderation utility that cares about age/inactivity in the first place... this here is an important user experience change.
Though, it compliments very well with #806 in my opinion:
- Hide game rooms that are not intended to be joined (started drafts for example - people leave at different times because their matches finished earlier while others are still playing, some want to pair for r2 or chat about the draft pool etc. - so the room ends up showing in the list of available games while it's still occupied)
- and (#806) delete outdated/old game rooms completely after longer inactivity

What does @poixen thinks here?

**Comment by Daenyth** [comment]
I think we should create a new type of "game" which is actually an event manager. Players "enter" instead of ready and it allows a way to manage pairings. It could show "started" and so on. It's quite ambitious. It would fully solve the stale draft issue. No one cares about actual game games that are old, I believe.

**Comment by Daenyth** [comment]
cc @derflippi

**Comment by Daenyth** [comment]
Let me brainstorm and I will write a design proposal for "tournament" games

**Comment by Daenyth** [comment]
http://strawpoll.me/5971191 btw

**Comment by derflippi** [comment]
Thank your for cc'ing me. Will provide comprehensive input later.

**Comment by tooomm** [comment]
> No one cares about actual games that are old, I believe.

Well, old games mess around with the actual (filtered) list of available games and make it less useful. People happen to join outdated games a lot I think. Happens to me frequently as well. :)
Let's take the draft room example again... they often get available again after ~30min because the drafting is over and the r1 pairings are done & people leave the room because it's no longer needed;
other drafts happen to search roughly the same amount of time to find a full group of 8 people or someone left during the drafting and they need another person to fill up the draft again.
So you can't distinguish both just by checking the age/time, you just see two draft rooms that are 6/8 and 30min old. But let's see what the poll brings up!

Plus server operators might not want to have dead rooms float around, increase the workload of their moderators and decrease the experience of their users. (@woogerboy21)
Wasn't that the initial intention of 806? --> https://github.com/Cockatrice/Cockatrice/pull/806#issuecomment-153300754

<br>
A totally new game type or tournament handling might be something nice for the future.
But for now the proposed tick box will solve mostly all draft issues and help with game rooms in general.

(I voted for `Stale drafts and pvp games are both a problem`, but I think drafts - and maybe other formats/game types that I can't think of right now - are a bigger problem than normal 1on1 games!)

**Comment by Daenyth** [comment]
> No one cares about actual games that are old, I believe.

I assumed this, it's part of why I posted the poll. I think the results so far show that I'm not correct.

**Comment by Daenyth** [comment]
> (I voted for `Stale drafts and pvp games are both a problem`, but I think drafts - and maybe other formats/game types that I can't think of right now - are a bigger problem than normal 1on1 games!)

I agree that drafts are larger. I meant to put that as multiple options

**Comment by Daenyth** [comment]
> But for now the proposed tick box will solve mostly all draft issues and help with game rooms in general.

I don't want to expand the software with something that only partially addresses things and doesn't necessarily help the general case. That's the path leading to bloat. I'm not necessarily arguing against this feature specifically, but I want us to discuss the options.

Anything we add that goes across client/server boundary has to stay supported pretty much forever.

I'd be more in favor of the server just keeping track of recent activity and then using the existing kick action to implicitly empty the room. That wouldn't require any changes to the protocol and we're not locked into the choice. We can remove the behavior later if it's not helpful and we can change it. If we add something to the protocol it's quite hard to change. You saw how bad the expeditions "required feature" thing was - and this would be worse

**Comment by LethalPigeon7** [comment]
Sorry for potentionally coming out as rude, but I don't understand, this supposedly incredibly complicated to implement solution of "tournament rooms" only solves half the problem and leaves the other, which we've proven to be relevant unchecked. My suggestion solves both of these specific problems in what is in my opinion a elegant and simple way, by comparison at least, if nothing else.  
I fully understand the choice not to go for it because "it would have to stay supported forever / it would be hard to change", but I'd like the fact that this is the only real downside aknowledged (or disuputed).
I can see the genius behind the tournament rooms more than clearly, but not as a solution to this specific, relevant problem.

**Comment by Daenyth** [comment]
I think I'm not being clear.

> Buddies only" rooms of people whose buddy list I'm not on, and rooms of people whose ignore list I am on falling under "unavailable games" for the purpouses of the "show unavailable games" tickbox.

Not possible given the current design of buddy lists, which we don't want to change at the moment. This is helped by user rooms because it would be a smaller community with less incentive to make buddy only rooms.

> A "make room invisible" tickbox that autoticks on when the room fills (and only ticks off manually).

I'm open to ideas like this (and I think it's been proposed in some form or another in other tickets) but I don't want it to be part of the client<->server protocol, I'd like the server to just close a game by kicking everyone from it if there's no actions at all for some set length of time. This avoids the maintenance issue because we don't need to change the protocol.

**Comment by LethalPigeon7** [comment]
The first part being unreal has been made perfectly clear, sorry if I haven't made THAT clear :)  
What I don't understand so clearly now is "I don't want it to be part of the client<->server protocol" mostly because I have no clue what that implies from the point of a developer.  
Specifically "the maintenance issue", where in this theoretical process is maintenance involved?

**Comment by Daenyth** [comment]
The client and server have a protocol that lets them talk to each other. If we add new types of communication, it increases the surface area of this protocol, making it larger and more complicated. This means it's harder to maintain the app in general and it will make it slower to add new features or work on alternate client or server implementations. If we add something to the protocol and we later decide we don't like the way it works, it's very hard to change, because once it's released, thousands of people have it, and we need to either make it keep working or break everyone's version and force them to get a different one.

If it's a server-side-only change then none of those concerns apply; we can add or remove or change the feature as much as we want and users don't need to do anything.

**Comment by LethalPigeon7** [comment]
Ah, wonderfully explained. Thank you. I'd appreciate the magical tickbox being kept in mind, but the "close rooms after set time of inactivity" will solve these problems well enough. As for the "set time lenght of time" after which the room closes, I'd like to point out that less known limited formats tend to take up to 30 minutes fairly often. Once again, thanks. Glad to see this is going somewhere.

**Comment by Daenyth** [comment]
> As for the "set time lenght of time"

I probably would start off with something like 1 hour of no chat/game actions to be safe.

The reason I haven't done this before is that it's actually slightly trickier than it seems at first glance.

If we include "chat" as activity that resets the timer, an AFK host that has someone join, ask "are you there", then leave, would count as activity, and the afk host remains. If we don't count chat as activity, then a room people are using for chat rather than gameplay would be closed even when active. If we count activity per-player, that's actually rather a lot of extra data for the server to keep track of (though it's probably ok, we'd have to write it then measure)

**Comment by derflippi** [comment]
When you join the chatrooms, you're provided with "recent activity" of that room. I believe doing the same for game-rooms might solve the problem. 
A player joins a game and sees the last activity was 25 minutes ago, someone asking "anyone for a r2?" and that way he knows it's done. 

About the AFK reset timer, maybe it's a useful solution to only count host activity for AFK, OR count host inactivity of X minutes (40?) as necessary requirement and add any-player inactivity of Y minutes (5?) as another necessary requirement.

**Comment by Daenyth** [comment]
Thank you for the insight flippi.

> When you join the chatrooms, you're provided with "recent activity" of that room. I believe doing the same for game-rooms might solve the problem. 

@woogerboy21 Do you still have the server stats page anywhere? What's a typical number of open games? 2000? I suppose it probably would only amount to a few extra mb of ram usage.

**Comment by woogerboy21** [comment]
Stats page still exists. I don't recall what the peak game count typically
is off the top of my head but I want to say they have been as high as 450 .

http://cockatrice.woogerworks.com/statistics.php

As far as ram usage , it most likely wouldn't be very much if only the last
say 20 lines were stored.  If you stored everything discussed in each game
it could potentially add up to large amounts pretty quickly.

**Comment by ZeldaZach** [comment]
I/O of writing, deleting, and rewriting on that @woogerboy21

**Comment by derflippi** [comment]
See also #544

**Comment by LethalPigeon7** [comment]
Sorry to go back to this, but I feel this falls under this suggestion. While I get that making games I cant join invisible to me is hard, can we at least lower the limit of buddy games? You know, to 1 maybe. I present the multiple buddy games feature being used to its fullest.
![welp](https://cloud.githubusercontent.com/assets/7950438/11229052/04936fec-8d92-11e5-80e9-7e9897c80d7c.png)

**Comment by Daenyth** [comment]
I don't see a compelling reason to set a limit of games you can create so low.

I could see hiding buddy games under "unavailable", or perhaps having an extra toggle specifically for it.

Maybe if we created a relevancy rating that was the default game sort. A combination of password, buddy only, game age, open slots..

**Comment by LethalPigeon7** [comment]
Absolutely right, how could I have doubted tickboxes, no joke the best
thing ever, hail tickbox (no this isnt sarcasm).

**Comment by Daenyth** [comment]
I can't tell whether you're being sincere or extremely sarcastic, but if you do have other ideas for how we can expose better UI workflows I'm always open to discussing them.

**Comment by Daenyth** [comment]
I think the comments from the first post have been addressed. Please reopen if needed.
