### ISSUE TITLE
Support for <tablerow> in tokens.xml

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#232]
Can we have support for `<tablerow>`; in tokens.xml?

Alternatively, can all tokens with `<pt>`; be assigned to row 2 and tokens without the tag to row 1?

Tokens that should be in row 1:
* Gold
* Land Mine
* Emblems
* Poison counter

**Comment by ctrlaltca** [comment]
Tablerow is already working for tokens. I suppose it has been fixed in this last year by another commit.

**Comment by Psithief** [comment]
@ctrlaltca 
You haven't tested this. It hasn't changed.

Emblems and non-creature tokens are still appearing in the top row.

**Comment by ZeldaZach** [comment]
@Psithief You can add the `<row>` tag to the tokens to make them appear in the proper rows

**Comment by Psithief** [comment]
Someone changed it to <row> from <tablerow> then? Okay.

**Comment by Psithief** [comment]
@ZeldaZach 
I tried replacing <tablerow> with <row> and the tokens file is completely broken by this change.

Are you sure that is the right tag?

**Comment by ZeldaZach** [comment]
It's 4am so I'll look into it in about 17 hours or so.

**Comment by Psithief** [comment]
I think this is the problem.

From `cockatrice/src/player.cpp`
```c++
void Player::actCreateToken()
{
    DlgCreateToken dlg(predefinedTokens);
    if (!dlg.exec())
        return;

    lastTokenName = dlg.getName();
    lastTokenPT = dlg.getPT();
    if (CardInfo *correctedCard = db->getCardBySimpleName(lastTokenName, false)) {
        lastTokenName = correctedCard->getName();
        if (lastTokenPT.isEmpty())
            lastTokenPT = correctedCard->getPowTough();
    }
    lastTokenColor = dlg.getColor();
    lastTokenAnnotation = dlg.getAnnotation();
    lastTokenDestroy = dlg.getDestroy();
    aCreateAnotherToken->setEnabled(true);
    
    actCreateAnotherToken();
}

void Player::actCreateAnotherToken()
{
    Command_CreateToken cmd;
    cmd.set_zone("table");
    cmd.set_card_name(lastTokenName.toStdString());
    cmd.set_color(lastTokenColor.toStdString());
    cmd.set_pt(lastTokenPT.toStdString());
    cmd.set_annotation(lastTokenAnnotation.toStdString());
    cmd.set_destroy_on_zone_change(lastTokenDestroy);
    cmd.set_x(-1);
    cmd.set_y(0);
    
    sendGameCommand(cmd);
}

```

If tablerow is `y` then it's always set to `0`.

**Comment by ctrlaltca** [comment]
The tag is still <tablerow>, i suppose @ZeldaZach just confused the tag name.
I totally misunderstood the issue, sorry for that, i'm now looking for a solution.

**Comment by Psithief** [comment]
:+1:

**Comment by ctrlaltca** [comment]
Opened #1166 to address this issue. I'd be grateful if you could have a look at it.
