### ISSUE TITLE
Updating.

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2678]
Well i feel for it, nice troll job. Went to update and now i lost cockatrice again. I cannot get back on. the update did not function, it uninstalled my original cockatrice. and i cannot get back i tried to download the Gatewatch versions and they do not work. ill explain why.

Cockatrice-Gatewatchers-win-x86  Work, got on cock but would not go online it said i needed to update. i clikc update and the client stops and shuts down.
Cockatrice-Gatewatchers-win-x86_64 Says i am missing some file.

This happenes EVERY single time i try to update. hence i try to NOT update as the process is a never ending  confusion. please help.

**Comment by Daenyth** [comment]
Which version did you try to install? What was the error message.

Also obviously we aren't trolling you. Saying shit like that just makes you
look like an ass and makes us less likely to want to spend our free time
helping you.

**Comment by ZeldaZach** [comment]
We changed how the updater works, you'll need to download a copy from http://cockatrice.github.io in order to play. Older builds won't have updaters working as we don't use Bintray anymore.

**Comment by Jinxstands4Jinx** [comment]
well no offense i knew this would happen....it always does.  updating this is always a pita. Both of the one i listed. I was on cockatrice before i tried to install. and now i cannot connect at all.

**Comment by tooomm** [comment]
About the missing files you most likely just need to read [this](https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcpxxxdll-was-not-found) in our troubleshooter in the wiki.
Has bin there forever btw and is also linked on our homepage. :)

Gatewatchers is a pretty old version and don't expect it to work or that all servers are still supporting it. A lot changed in between. You really have to run a more recent version.

What happens if you download the win file form our page as @ZeldaZach suggested?
(i'm just assuming here that you use windows, because you didn't use the template and told us this important information for your operating system)

@Daenyth his updating problem from this old version might fail because somebody deleted the thopter release that we manually still had on bintray for this kind of reason - a smother transition of old clients.

**Comment by Jinxstands4Jinx** [comment]
well i am back where i started. still not fixed but back to exactly where i was when i tried to update to the beta so aftermath cards and the Second sun tool would be.

**Comment by tooomm** [comment]
I can't help you with that little of information. I have no idea where you have been before or what you actually did.

I'm sorry, looks like you need to deal with that on your own.

**Comment by Jinxstands4Jinx** [comment]
well i was here, i wanted to get to the Beta that had the aftermath cards Fixed and the Second sun toll included. Until i figure out how to fix these aftermaths Drafting AKH is basically out of the question since every aftermath will be an illegal deck. i have them fromthe oracle but not in their correct form.

[[Destined // Leadd]] does not work  but [[Destined]] does.

**Comment by Daenyth** [comment]
I don't believe that fix is in a full release version yet, but if you
change your settings to use the development snapshots for updates then the
update checker should get you there. Or download by hand from the releases
tab that's accessible from the main github repo page.

Zach since we haven't seen major issues on tits snapshot, do you want to
make a release so everyone gets that fix?

**Comment by tooomm** [comment]
Wizards decided to change the aftermath cards. Not our fault and nothing we can do about that.
We implemented the change in the newer versions to display their art etc., so you need to install a beta (and run the new Oracle installed alongside as well!) to get it working.

[[heaven // earth]] works perfectly for me!

>every aftermath will be an illegal deck

What do you mean? illegal deck?

**Comment by Jinxstands4Jinx** [comment]
Doing as you said Daeynth.  ok now i have the Approach Tool. Neat. checking for the aftermath fix.... still not working.  i am lost. forget it i have the newest piece. ill just have to deal with the aftermath thing.

**Comment by ctrlaltca** [comment]
What version are you running now?

**Comment by Jinxstands4Jinx** [comment]
2.3.17-beta004... thats what it says. but its fine. move on to more pressing matters.

**Comment by Daenyth** [comment]
Did you run Oracle

**Comment by Jinxstands4Jinx** [comment]
yes 5 times now. the only way i can see to get them to wrok is to use Tritoch's xml which means my tokens will no longer be linked to the correct places.... I rather have the tokens fixed than the aftermaths.

**Comment by Jinxstands4Jinx** [comment]
ok it finally refreshed itself. the Aftermaths are fixed.. not sure what or why but Not asking questions

**Comment by tooomm** [comment]
You had to run Oracle AFTER INSTALLING the beta... as I told you before.
How else should Oracle know about the changes and build the propper database!?

If you update Cockatrice, you always update Oracle as well. Oracle is a part of Cockatrice and Oracle builds your database. Cockatrice just uses it.

**Comment by Jinxstands4Jinx** [comment]
i did run the oracle after installing, and udpating.. like 5 times.

**Comment by Daenyth** [comment]
Sounds like you're all set

**Comment by Jinxstands4Jinx** [comment]
yeah its fine now, like i said. thx for the help.
