### ISSUE TITLE
Bug: Undo draw function fails after rearranging cards

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#326]
If you draw a card, then rearrange the freshly drawn card in your hand, the undo draw function will not work anymore. (presumably because it can't track the card in its new position.)

**Comment by anoda9** [comment]
It would be really great if this were fixed. For tournaments run on magic-league, being able to undo the draw or not is the difference between a warning and a game loss.

**Comment by Daenyth** [comment]
I'm fairly certain this is going to be difficult to the point where you
shouldn't rely on it happening any time soon. The server doesn't store old
game states, undo draw is a special case. We'd need to rewrite how the game
states are managed.

I'd like to get more robust event control in at some point, but it's a
*long* way away

**Comment by ZeldaZach** [comment]
This is still an issue for us, and pops up very often in tournament play.

**Comment by knitknit** [comment]
Notes to self:

- https://github.com/Cockatrice/Cockatrice/blob/bec02b495299992b4210a8cc3724ca63679d7616/common/server_player.cpp#L360-L367 looks to be of interest
- `lastDrawList` stores IDs for last drawn card(s)
  * Is cleared in `clearZones()`
    - Occurs in `cmdConcede(...)` and `prepareDestroy()`
    - Can probably ignore this
  * Is appended to in `drawCards(...)`: https://github.com/Cockatrice/Cockatrice/blob/bec02b495299992b4210a8cc3724ca63679d7616/common/server_player.cpp#L311
  * In `moveCard(...)`, if `startzone = "hand"` then has specific card ID removed (if undoing) or is fully cleared (if moving): https://github.com/Cockatrice/Cockatrice/blob/bec02b495299992b4210a8cc3724ca63679d7616/common/server_player.cpp#L427-L433
  * Has last popped off in `cmdUndoDraw(...)`, which then calls `moveCard(...)` with `undoingDraw = true`: https://github.com/Cockatrice/Cockatrice/blob/bec02b495299992b4210a8cc3724ca63679d7616/common/server_player.cpp#L1085-L1089
- I would suspect that undo draw doesn't work after moving cards around in hand because moving cards in hand somehow invokes `moveCard(...)`, which clears the last draw list, but need to confirm this
- Seems like card ordering is all client-side though, so not clear what exactly would trigger the draw list to be empty
