### ISSUE TITLE
Tokens don't land where you drag them

### ISSUE THREAD

**Issue by MotherofRuins** [Cockatrice/Cockatrice#4264]
**System Information:**
Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 7 SP 1 (6.1)
Build Architecture: 64-bit
Qt Version: 5.12.9
System Locale: en_US
Install Mode: Standard

_______________________________________________________________________________________

When a permanent is moved, there are certain discrete locations it will move to.  I'll call those landing pads, or just pads.  Tokens are behaving differently from cards.  If you move a token to a pad where there are already one or more other permanents, it goes there just fine.  But if the pad is empty, the token lands on the pad to the left.

_______________________________________________________________________________________

Put a card on the battlefield.  Create a token.  Place it atop the card (this works fine).  Try to place it one pad to the right of the card.  It jumps to the card.  Try to place it two pads to the right.  It lands one pad to the right.

**Comment by ZeldaZach** [comment]
This is a known issue that was fixed #4236

**Comment by ZeldaZach** [comment]
You can grab a beta build for you/your server, if necessary

**Comment by ebbit1q** [comment]
note that this is already implemented on public servers, only the local game feature will still have this bug
