### ISSUE TITLE
macOS 12/13 occasionally failing

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4925]
macOS 12 example:
https://github.com/Cockatrice/Cockatrice/actions/runs/6614690847/job/17965213572?pr=4922
```
  CPack: - Run preinstall target for: Cockatrice
  CPack: - Install project: Cockatrice []
  CPack: Create package
  CPack Error: Error executing: osascript "/Users/runner/work/Cockatrice/Cockatrice/cmake/CMakeDMGSetup.script" "Cockatrice"
  CPack Error: Error executing custom script on disk image.
  osascript: can't open default scripting component.
  
  CPack Error: Problem compressing the directory
  CPack Error: Error when generating package: Cockatrice
  make: *** [package] Error 1
  Error: Process completed with exit code 2.
```

macOS 13 example:
https://github.com/Cockatrice/Cockatrice/actions/runs/6632768476/job/18019167204?pr=4871
```
  CPack: - Run preinstall target for: Cockatrice
  CPack: - Install project: Cockatrice []
  CPack: Create package
  CPack Error: Error executing: /usr/bin/hdiutil create -ov -srcfolder "/Users/runner/work/Cockatrice/Cockatrice/build/_CPack_Packages/OSX/DragNDrop/Cockatrice-2.9.0-custom(6f88419)" -volname "Cockatrice" -fs "HFS+" -format UDRW "/Users/runner/work/Cockatrice/Cockatrice/build/_CPack_Packages/OSX/DragNDrop/temp.dmg"
  CPack Error: Error generating temporary disk image.
  hdiutil: create failed - Resource busy
  
  CPack Error: Problem compressing the directory
  CPack Error: Error when generating package: Cockatrice
  make: *** [package] Error 1
  Error: Process completed with exit code 2.
```

<br>

A rerun can sometimes fix the issue.

**Comment by tooomm** [comment]
Unfortunately, #4961 is not solving this just yet.

See the CI run on master after merging:
- First run failing: https://github.com/Cockatrice/Cockatrice/actions/runs/7229159667/attempts/1
- Second run failing: https://github.com/Cockatrice/Cockatrice/actions/runs/7229159667/attempts/2
- Third run succeeding: https://github.com/Cockatrice/Cockatrice/actions/runs/7229159667/attempts/3

Also see Elarnons note in his PR. I had to rerun it as well to get a successful build for others to test.

**Comment by ZeldaZach** [comment]
Looks related to https://github.com/actions/runner-images/issues/7522

**Comment by tooomm** [comment]
Upstream issue: https://gitlab.kitware.com/cmake/cmake/-/issues/25671

**Comment by tooomm** [comment]
We can close this as it's an upstream issue that needs to get fixed in CPack/CMake.
Once a fix is available, we will get it down the line.

**Comment by ebbit1q** [comment]
this is still a problem unfortunately, when will cmake fix this?

```
  CPack Error: Error executing: /usr/bin/hdiutil detach "/Volumes/Cockatrice"
  CPack Error: Error detaching temporary disk image.
```

**Comment by ebbit1q** [comment]
https://github.com/actions/runner-images/issues/7522#issuecomment-1566746364

seems interesting

**Comment by ebbit1q** [comment]
it's clearly an issue in the runners, not cmake

**Comment by ebbit1q** [comment]
this might be a workaround we can use too https://github.com/HEXRD/hexrdgui/pull/1768/files
