### ISSUE TITLE
Very large decks make cockatrice hang up/crash

### ISSUE THREAD

**Issue by cemper** [Cockatrice/Cockatrice#67]
Hi,
I had written a small script to create a COD-deck including one of every card ever printed (plus a lot of basic lands) to play a casual fun game with it. Unfortunately, upon loading this deck in a lobby, cockatrice hung up for several minutes - then, after it had finished loading, when you started the game, cockatrice stopped responding altogether. This is quite a nuisance, since when you reconnect to the server, cockatrice will try to resume the ongoing game, thereby loading the deck and crashing again.

Steps to reproduce:
- Have a large deck (for example this one that I used: https://www.dropbox.com/s/rx4fx0kvwr60k7a/all-deck.cod)
- Try to use it to play a game

**Comment by woogerboy21** [comment]
Is this issue resolved with the most recent cache options?

**Comment by ctrlaltca** [comment]
@woogerboy21 The main issue about cockatrice eating up all RAM and trashing the system is resolved. After testing the 17k cards deck, i saw there's still an issue: when loading a deck in the deck editor / deck selection screen in the game, we'll cache the card images for all the cards in the deck (hint: cacheCardPixmaps() ).
With a deck of 17k cards, this means some time at 100% cpu while cockatrice fills 2GB of RAM with images with the first hundreds of cards, and then unloads them to make room for the following thousands. I think we could just cap the max number of precached cards images to avoid this issue.

**Comment by uber5001** [comment]
Still having issues loading a 65k card deck. When I load it, my rig takes about a minute to finish loading. When my friend loads it... well... he's still waiting for cockatrice to respond at the moment. It's been 10 minutes so far.

**Comment by ctrlaltca** [comment]
65k cards is a really huge deck, but a nice test indeed.

> When both players clicked ready to start, my friend's client crashed, and my client took about 3 minutes to start the game.

It would be nice to understand how much of that wait time is due to CPU calculations, how much to other tasks (like allocating memory for he cards, etc..) and how much is spend sending the huge card list to the server, and how much is due to calculations on the server.

> It took 5 minutes to load the View Library GUI. Finding the card took a few second since it was a basic land, but the GUI only visually updated every second or so. 

I don't think we have really good optimization margins here, if not leveraging the GPU 

> Shuffling the library afterwards took about a minute.

Shuffling happens on the server, so i suppose the server got a minute-long CPU spike. We should probably add some mitigations to this possible denial of service.

**Comment by woogerboy21** [comment]
If you happen to know a time frame I can look at the server side statistics
and see if it impacted the processors on the server.
Thanks

**Comment by uber5001** [comment]
The whole game took about two hours, and was somewhere around the time 7-9 pm UTC/GMT, today (Wednesday, August 17, 2016). There was only one shuffle performed during that game, iirc.

**Comment by uber5001** [comment]
> Shuffling happens on the server, so i suppose the server got a minute-long CPU spike. We should probably add some mitigations to this possible denial of service.

For shuffling (assuming that shuffling is even part of the issue), could the shuffling instead be performed on each draw? I don't mean to shuffle the entire library on each draw. I mean you could mark the relevant sections of the library as "shuffled", and just draw randomly from that section, as needed.

**Comment by woogerboy21** [comment]
I would be interested in seeing if you could repeat the test as I don't
have the performance data specifically on the processor usage during that
time (only keep a few hours worth of that data).   But I can say that there
doesn't appear to be any major player drops making me question if there was
a spike, that the spike took that long to recover.

**Comment by uber5001** [comment]
I'll do that now. Just going to join a game by myself and shuffle some cards around.

**Comment by woogerboy21** [comment]
Thats a whoops ...

**Comment by uber5001** [comment]
I don't think this has anything to do with loading images, unless the same image is getting loaded many times for some reason.

Testing with a deck of 100k of the same card.
Time to load deck: 33 minutes
Time to start game: 5 minutes
Time to load "view library" window: 17 minutes
Time to shuffle deck: 1 minute
Time to concede: 5 minutes

**Comment by uber5001** [comment]
Crashed once while attempting to load this deck.

Testing with a deck of 10k cards, each of them being unique.
Time to load deck: 15 seconds
Time to start game: 15 seconds
Time to view library: 5 seconds
Time to shuffle deck: <1 second
Time to concede: 20 seconds
